Resources:
  aBucket43B84104:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: EventS3LambdaStack/aBucket/Resource
  aBucketNotificationsC5696022:
    Type: Custom::S3BucketNotifications
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - BucketNotificationsHandler050a0587b7544547bf325f094a3db8347ECC3691
          - Arn
      BucketName:
        Ref: aBucket43B84104
      NotificationConfiguration:
        LambdaFunctionConfigurations:
          - Events:
              - s3:ObjectCreated:*
            LambdaFunctionArn:
              Fn::GetAtt:
                - EchoS339537F1B
                - Arn
    DependsOn:
      - EchoS3AllowBucketNotificationsFromEventS3LambdaStackaBucket150EF2AD17E759C4
    Metadata:
      aws:cdk:path: EventS3LambdaStack/aBucket/Notifications/Resource
  EchoS3ServiceRole3F5320CC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: EventS3LambdaStack/EchoS3/ServiceRole/Resource
  EchoS3ServiceRoleDefaultPolicy97FD7C12:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - aBucket43B84104
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - aBucket43B84104
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: EchoS3ServiceRoleDefaultPolicy97FD7C12
      Roles:
        - Ref: EchoS3ServiceRole3F5320CC
    Metadata:
      aws:cdk:path: EventS3LambdaStack/EchoS3/ServiceRole/DefaultPolicy/Resource
  EchoS339537F1B:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersdb4631b1386e61a8b4e5ec96b95a8ce1b74eae04c1db9dd22e7b733cabf4bda7S3Bucket5B2F70FC
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersdb4631b1386e61a8b4e5ec96b95a8ce1b74eae04c1db9dd22e7b733cabf4bda7S3VersionKeyFA23B7E2
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersdb4631b1386e61a8b4e5ec96b95a8ce1b74eae04c1db9dd22e7b733cabf4bda7S3VersionKeyFA23B7E2
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - EchoS3ServiceRole3F5320CC
          - Arn
      Runtime: nodejs8.10
      Environment:
        Variables:
          SOME: value
    DependsOn:
      - EchoS3ServiceRoleDefaultPolicy97FD7C12
      - EchoS3ServiceRole3F5320CC
    Metadata:
      aws:cdk:path: EventS3LambdaStack/EchoS3/Resource
      aws:asset:path: /Users/leo/git/cdk-talk-examples/code/event_s3_lambda/funcs/echo_s3
      aws:asset:property: Code
  EchoS3AllowBucketNotificationsFromEventS3LambdaStackaBucket150EF2AD17E759C4:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - EchoS339537F1B
          - Arn
      Principal: s3.amazonaws.com
      SourceAccount:
        Ref: AWS::AccountId
      SourceArn:
        Fn::GetAtt:
          - aBucket43B84104
          - Arn
    Metadata:
      aws:cdk:path: EventS3LambdaStack/EchoS3/AllowBucketNotificationsFromEventS3LambdaStackaBucket150EF2AD
  BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleB6FB88EC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: EventS3LambdaStack/BucketNotificationsHandler050a0587b7544547bf325f094a3db834/Role/Resource
  BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleDefaultPolicy2CF63D36:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: s3:PutBucketNotification
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleDefaultPolicy2CF63D36
      Roles:
        - Ref: BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleB6FB88EC
    Metadata:
      aws:cdk:path: EventS3LambdaStack/BucketNotificationsHandler050a0587b7544547bf325f094a3db834/Role/DefaultPolicy/Resource
  BucketNotificationsHandler050a0587b7544547bf325f094a3db8347ECC3691:
    Type: AWS::Lambda::Function
    Properties:
      Description: AWS CloudFormation handler for "Custom::S3BucketNotifications" resources (@aws-cdk/aws-s3)
      Code:
        ZipFile: >-
          exports.handler = (event, context) => {
              const s3 = new (require('aws-sdk').S3)();
              const https = require("https");
              const url = require("url");
              log(JSON.stringify(event, undefined, 2));
              const props = event.ResourceProperties;
              if (event.RequestType === 'Delete') {
                  props.NotificationConfiguration = {}; // this is how you clean out notifications
              }
              const req = {
                  Bucket: props.BucketName,
                  NotificationConfiguration: props.NotificationConfiguration
              };
              return s3.putBucketNotificationConfiguration(req, (err, data) => {
                  log({ err, data });
                  if (err) {
                      return submitResponse("FAILED", err.message + `\nMore information in CloudWatch Log Stream: ${context.logStreamName}`);
                  }
                  else {
                      return submitResponse("SUCCESS");
                  }
              });
              function log(obj) {
                  console.error(event.RequestId, event.StackId, event.LogicalResourceId, obj);
              }
              // tslint:disable-next-line:max-line-length
              // adapted from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-cfnresponsemodule
              // to allow sending an error messge as a reason.
              function submitResponse(responseStatus, reason) {
                  const responseBody = JSON.stringify({
                      Status: responseStatus,
                      Reason: reason || "See the details in CloudWatch Log Stream: " + context.logStreamName,
                      PhysicalResourceId: event.PhysicalResourceId || event.LogicalResourceId,
                      StackId: event.StackId,
                      RequestId: event.RequestId,
                      LogicalResourceId: event.LogicalResourceId,
                      NoEcho: false,
                  });
                  log({ responseBody });
                  const parsedUrl = url.parse(event.ResponseURL);
                  const options = {
                      hostname: parsedUrl.hostname,
                      port: 443,
                      path: parsedUrl.path,
                      method: "PUT",
                      headers: {
                          "content-type": "",
                          "content-length": responseBody.length
                      }
                  };
                  const request = https.request(options, (r) => {
                      log({ statusCode: r.statusCode, statusMessage: r.statusMessage });
                      context.done();
                  });
                  request.on("error", (error) => {
                      log({ sendError: error });
                      context.done();
                  });
                  request.write(responseBody);
                  request.end();
              }
          };
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleB6FB88EC
          - Arn
      Runtime: nodejs8.10
      Timeout: 300
    DependsOn:
      - BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleDefaultPolicy2CF63D36
      - BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleB6FB88EC
    Metadata:
      aws:cdk:path: EventS3LambdaStack/BucketNotificationsHandler050a0587b7544547bf325f094a3db834/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.15.0,@aws-cdk/assets=1.15.0,@aws-cdk/aws-apigateway=1.15.0,@aws-cdk/aws-applicationautoscaling=1.15.0,@aws-cdk/aws-autoscaling-common=1.15.0,@aws-cdk/aws-cloudwatch=1.15.0,@aws-cdk/aws-dynamodb=1.15.0,@aws-cdk/aws-ec2=1.15.0,@aws-cdk/aws-events=1.15.0,@aws-cdk/aws-iam=1.15.0,@aws-cdk/aws-kms=1.15.0,@aws-cdk/aws-lambda=1.15.0,@aws-cdk/aws-lambda-event-sources=1.15.0,@aws-cdk/aws-s3=1.15.0,@aws-cdk/aws-s3-assets=1.15.0,@aws-cdk/aws-s3-notifications=1.15.0,@aws-cdk/aws-sns=1.15.0,@aws-cdk/aws-sns-subscriptions=1.15.0,@aws-cdk/aws-sqs=1.15.0,@aws-cdk/aws-ssm=1.15.0,@aws-cdk/core=1.15.0,@aws-cdk/cx-api=1.15.0,@aws-cdk/region-info=1.15.0,jsii-runtime=node.js/v12.9.1
    Condition: CDKMetadataAvailable
Parameters:
  AssetParametersdb4631b1386e61a8b4e5ec96b95a8ce1b74eae04c1db9dd22e7b733cabf4bda7S3Bucket5B2F70FC:
    Type: String
    Description: S3 bucket for asset "db4631b1386e61a8b4e5ec96b95a8ce1b74eae04c1db9dd22e7b733cabf4bda7"
  AssetParametersdb4631b1386e61a8b4e5ec96b95a8ce1b74eae04c1db9dd22e7b733cabf4bda7S3VersionKeyFA23B7E2:
    Type: String
    Description: S3 key for asset version "db4631b1386e61a8b4e5ec96b95a8ce1b74eae04c1db9dd22e7b733cabf4bda7"
  AssetParametersdb4631b1386e61a8b4e5ec96b95a8ce1b74eae04c1db9dd22e7b733cabf4bda7ArtifactHash86E5233E:
    Type: String
    Description: Artifact hash for asset "db4631b1386e61a8b4e5ec96b95a8ce1b74eae04c1db9dd22e7b733cabf4bda7"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

